version: '3.1'
services:
   
   redis:
     image: redis:alpine
     restart: always
     ports:
       - '6379:6379'

  #  planetearth:
  #    image: planetearth
  #    build:
  #     context: .
  #     dockerfile: planet-earth/Dockerfile
  #    depends_on:
  #     - redis
  #    ports:
  #      - "4001:3000"

  #  planetmars:
  #   #  image: planetmars
  #    build:
  #     context: .
  #     dockerfile: planet-mars/Dockerfile
  #    depends_on:
  #     - planet-earth
  #     - redis
  #    ports:
  #      - "4002:3001"


  #  translator:
  #    image: earth-mars-translator
  #    build:
  #     context: .
  #     dockerfile: translator/Dockerfile
  #    depends_on:
  #     - planetearth
  #     - planetmars
  #     - redis
  #   #  ports:
  #   #    - ""