version: '3.1'
services:
   
   redis:
     image: redis:alpine
     restart: always
     ports:
       - '6379:6379'

   planet-earth:
     image: planet-earth
     build:
      context: ./planet-earth
      dockerfile: Dockerfile
     environment:
      - REDIS_HOST=redis
     depends_on:
      - redis
     ports:
       - "3000:3000"

   planet-mars:
     image: planet-mars
     build:
      context: ./planet-mars
      dockerfile: Dockerfile
     environment:
      - REDIS_HOST=redis
     depends_on:
      - planet-earth
      - redis
     ports:
       - "3001:3001"


   translator:
     image: earth-mars-translator
     build:
      context: ./translator
      dockerfile: Dockerfile
     environment:
      - REDIS_HOST=redis
     depends_on:
      - planet-earth
      - planet-mars
      - redis
    #  ports:
    #    - ""